version: "3"
services:
  app:
    ports:
      - '80:80'
      - '443:443'
  mongo:
    volumes:
      - makersights:/data/db
    ports:
      - "27017:27017"
volumes:
  makersights:
    external: true